EMAIL_REGEXP = %r{\A(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}\Z}xi
AUTH_TOKEN_EXPIRATION = 3.weeks
PER_PAGE = 10
COMPANY_NAME = ENV["company_name"] || 'DoubleBit Consulating'
EXCEPTION_SENDER = ENV["exception_sender"] || 'notifier@doublebitconsulting.com'
DEVISE_MAILER = ENV["devise_sender"] || 'info@doublebitconsulting.com'
PRODUCTION_HOST = ENV["production_host"] || '54.200.157.85'
STAGING_HOST = ENV["staging_host"] || '54.68.73.69'
S3_BUCKET_NAME = ENV["s3_bucket_name"] || 'www.ers.com'
S3_STAGING_BUCKET_NAME = ENV["s3_staging_bucket_name"] || 'staging.ers.com'