Date::DATE_FORMATS.merge!(day_month_date: "%^A %-m/%-d")
Date::DATE_FORMATS.merge!(month_date: "%m/%d")
Date::DATE_FORMATS.merge!(abb_day_month_date: "%a %-m/%-d")
Date::DATE_FORMATS.merge!(day: "%A")
Date::DATE_FORMATS.merge!(day_month_name_date: "%A, %B %e")
Date::DATE_FORMATS.merge!(abbr_day: "%a")
Date::DATE_FORMATS.merge!(date: "%Y-%m-%d")
Date::DATE_FORMATS.merge!(day_date_month_year: "%^A, %b %d %Y")
Date::DATE_FORMATS.merge!(month_str_date: "%B %-d")
Date::DATE_FORMATS.merge!(month_str_day_year: "%b %d %Y")
Time::DATE_FORMATS.merge!(day_date_month_year_time: "%^A, %b %d %Y, %-I:%M %p")
Time::DATE_FORMATS.merge!(day_month_year_time: "%b %d %Y, %-I:%M %P")
Time::DATE_FORMATS.merge!(time_day_month_date: "%I:%M %P, %A, %b %d")
Time::DATE_FORMATS.merge!(time: "%-I:%M %p")
Time::DATE_FORMATS.merge!(time_hour: "%H:%M")
Time::DATE_FORMATS.merge!(hour_meridian: "%l%P")
Time::DATE_FORMATS.merge!(date_month_year: "%d %^B %Y")
